apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: deploysafe-health-check
  namespace: deploysafe

spec:
  metrics:
    - name: application-health
      provider:
        job:
          spec:
            backoffLimit: 0
            template:
              spec:
                restartPolicy: Never
                containers:
                  - name: curl
                    image: curlimages/curl:8.8.0
                    command:
                      - sh
                      - -c
                      - |
                        curl --fail http://deploysafe-preview-service:80/health