apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deploysafe-ingress
  namespace: deploysafe
spec:
  ingressClassName: nginx
  rules:
    - host: deploysafe.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: deploysafe-service
                port:
                  number: 80