apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: deploysafe-servicemonitor
  namespace: deploysafe
  labels:
    release: prometheus

spec:
  selector:
    matchLabels:
      app: deploysafe

  endpoints:
    - port: http
      path: /metrics
      interval: 15s